server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  jackson:
    default-property-inclusion: ALWAYS
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true
  #    url: jdbc:mysql://localhost:3305/pallete
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: root1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:db/data.sql
      mode: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: palletdb
jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 86400000 # ttl (초)


  servlet:
    multipart:
      max-file-size: 5MB
 # ttl (초)

